USE HomeLibrary;
GO

CREATE TABLE Publisher (
	Id BIGINT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(20) NOT NULL,
	Address NVARCHAR(200) NOT NULL,
	Phone NVARCHAR(20) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	Website NVARCHAR(200) NOT NULL
)

CREATE TABLE Book (
	Id BIGINT IDENTITY(1,1) PRIMARY KEY,
	Title NVARCHAR(100) NOT NULL,
	Description NVARCHAR(300),
	PublicationYear INT,
	PublisherId BIGINT,
	ISBN NVARCHAR(50) UNIQUE,
	PagesNumber INT NOT NULL CHECK (PagesNumber > 0),
	ContentsTable XML NOT NULL,
	FOREIGN KEY (PublisherId) REFERENCES Publisher(Id)
);

CREATE TABLE Author (
	Id BIGINT IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	MiddleName NVARCHAR(20),
	BirthDate DATE,
	DeathDate DATE,
	Description NVARCHAR(300),
);

CREATE TABLE Genre (
	Id BIGINT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE BookAuthor (
	BookId BIGINT NOT NULL,
	AuthorId BIGINT NOT NULL,

	PRIMARY KEY (BookId, AuthorId),
	FOREIGN KEY (BookId) REFERENCES Book(Id),
	FOREIGN KEY (AuthorId) REFERENCES Author(Id)
);

CREATE TABLE BookGenre (
	BookId BIGINT NOT NULL,
	GenreId BIGINT NOT NULL,

	PRIMARY KEY (BookId, GenreId),
	FOREIGN KEY (BookId) REFERENCES Book(Id),
	FOREIGN KEY (GenreId) REFERENCES Genre(Id)
);
